# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    # networks:
    #   - outside
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  was:
    image: helloworld-was:1.0
    # networks:
    #   - outside
    ports:
      - "3000:3000"

# networks:
#     outside: